/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp6.detodosa;

/**
 *
 * @author NoxiePC
 */
public class Ventanaprincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName());

    /**
     * Creates new form Ventanaprincipal
     */
    public Ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMGestionproductos = new javax.swing.JMenu();
        jMnGestionprod = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMnConsulnom = new javax.swing.JMenuItem();
        jMnConsulprecio = new javax.swing.JMenuItem();
        jMnConsulrubro = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        jMGestionproductos.setText("Administracion");
        jMGestionproductos.addActionListener(this::jMGestionproductosActionPerformed);

        jMnGestionprod.setText("Gestión de Productos");
        jMGestionproductos.add(jMnGestionprod);

        jMenuBar1.add(jMGestionproductos);

        jMenu4.setText("Consultas");

        jMnConsulnom.setText("Consulta por Nombre");
        jMnConsulnom.addActionListener(this::jMnConsulnomActionPerformed);
        jMenu4.add(jMnConsulnom);

        jMnConsulprecio.setText("Consulta por Precio");
        jMnConsulprecio.addActionListener(this::jMnConsulprecioActionPerformed);
        jMenu4.add(jMnConsulprecio);

        jMnConsulrubro.setText("Consulta por Rubro");
        jMnConsulrubro.addActionListener(this::jMnConsulrubroActionPerformed);
        jMenu4.add(jMnConsulrubro);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMGestionproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMGestionproductosActionPerformed

    private void jMnConsulnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsulnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConsulnomActionPerformed

    private void jMnConsulprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsulprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConsulprecioActionPerformed

    private void jMnConsulrubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsulrubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConsulrubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventanaprincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMGestionproductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnConsulnom;
    private javax.swing.JMenuItem jMnConsulprecio;
    private javax.swing.JMenuItem jMnConsulrubro;
    private javax.swing.JMenuItem jMnGestionprod;
    // End of variables declaration//GEN-END:variables
}
