/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp6.detodosa;

import java.util.TreeSet;

/**
 *
 * @author NoxiePC
 */
public class Ventanaprincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName());

    public static TreeSet<Producto> listaProductos = new TreeSet<>();
    
    public Ventanaprincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMnGestion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMnNombre = new javax.swing.JMenuItem();
        jMnPrecio = new javax.swing.JMenuItem();
        jMnRubro = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        jMenu5.setText("Administración");

        jMnGestion.setText("Gestión de Productos");
        jMnGestion.addActionListener(this::jMnGestionActionPerformed);
        jMenu5.add(jMnGestion);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Consultas");
        jMenu3.addActionListener(this::jMenu3ActionPerformed);

        jMnNombre.setText("Por Nombre");
        jMnNombre.addActionListener(this::jMnNombreActionPerformed);
        jMenu3.add(jMnNombre);

        jMnPrecio.setText("Por Precio");
        jMnPrecio.addActionListener(this::jMnPrecioActionPerformed);
        jMenu3.add(jMnPrecio);

        jMnRubro.setText("Por Rubro");
        jMnRubro.addActionListener(this::jMnRubroActionPerformed);
        jMenu3.add(jMnRubro);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMnGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnGestionActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Gestion ventanagestion = new Gestion();
        ventanagestion.setVisible(true);
        jDesktopPane1.add(ventanagestion);
    }//GEN-LAST:event_jMnGestionActionPerformed

    private void jMnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnNombreActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Listadonombre nombre = new Listadonombre();
        nombre.setVisible(true);
        jDesktopPane1.add(nombre);
    }//GEN-LAST:event_jMnNombreActionPerformed

    private void jMnPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnPrecioActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Listadoprecio precio = new Listadoprecio();
        precio.setVisible(true);
        jDesktopPane1.add(precio);
    }//GEN-LAST:event_jMnPrecioActionPerformed

    private void jMnRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnRubroActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Listadorubro rubro = new Listadorubro();
        rubro.setVisible(true);
        jDesktopPane1.add(rubro);
    }//GEN-LAST:event_jMnRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventanaprincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMnGestion;
    private javax.swing.JMenuItem jMnNombre;
    private javax.swing.JMenuItem jMnPrecio;
    private javax.swing.JMenuItem jMnRubro;
    // End of variables declaration//GEN-END:variables
}
